import Vue from 'vue';
import Alert from '@tailwindvue/tailwindvue/src/components/Alert';
import App from '@tailwindvue/tailwindvue/src/components/layout/App';
import Badge from '@tailwindvue/tailwindvue/src/components/Badge';
import Code from '@tailwindvue/tailwindvue/src/components/Code';
import CodeDemo from '@tailwindvue/tailwindvue/src/components/CodeDemo';
import Content from '@tailwindvue/tailwindvue/src/components/Content';
import Heading from '@tailwindvue/tailwindvue/src/components/Heading';
import Input from '@tailwindvue/tailwindvue/src/components/Input';
import Navbar from '@tailwindvue/tailwindvue/src/components/Navbar';
import Panel from '@tailwindvue/tailwindvue/src/components/Panel';
import Sidebar from '@tailwindvue/tailwindvue/src/components/Sidebar';
import Tab from '@tailwindvue/tailwindvue/src/components/Tab';
import TabbedCodeDemo from '@tailwindvue/tailwindvue/src/components/TabbedCodeDemo';
import Table from '@tailwindvue/tailwindvue/src/components/Table';
import TableColumn from '@tailwindvue/tailwindvue/src/components/TableColumn';
import TableHeading from '@tailwindvue/tailwindvue/src/components/TableHeading';
import TableRow from '@tailwindvue/tailwindvue/src/components/TableRow';
import Tabs from '@tailwindvue/tailwindvue/src/components/Tabs';

Vue.component('tw-alert', Alert);
Vue.component('tw-app', App);
Vue.component('tw-badge', Badge);
Vue.component('tw-code', Code);
Vue.component('tw-code-demo', CodeDemo);
Vue.component('tw-content', Content);
Vue.component('tw-heading', Heading);
Vue.component('tw-input', Input);
Vue.component('tw-navbar', Navbar);
Vue.component('tw-panel', Panel);
Vue.component('tw-sidebar', Sidebar);
Vue.component('tw-tab', Tab);
Vue.component('tw-tabbed-code-demo', TabbedCodeDemo);
Vue.component('tw-table', Table);
Vue.component('tw-table-column', TableColumn);
Vue.component('tw-table-heading', TableHeading);
Vue.component('tw-table-row', TableRow);
Vue.component('tw-tabs', Tabs);
